### PR TITLE
Change Cypress version

### PR DESCRIPTION
**Pull request by Aboullos**
Update package-lock.json  and yarn.lock file with Cypress 6.2.1 version

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Review by jenny-s51 — COMMENTED** [review]
@Aboullos I am not able to start cypress. Do you have any idea why this might be happening?

```
➜ sudo yarn start:cypress
Password:
yarn run v1.16.0
$ cd tests && npx cypress@6.2.1 open
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@6.2.1 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@6.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jenny/.npm/_logs/2021-01-27T15_23_49_146Z-debug.log
Install for [ 'cypress@6.2.1' ] failed with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Aboullos** [comment]
@jenny-s51 Can you try deleting the node_modules folder and installing it again?

**Comment by jenny-s51** [comment]
@Aboullos I tried deleting `node_modules` and ran `git clean -dfx` with a fresh install a few times but I'm still running into this

**Review by mfrances17 — COMMENTED** [review]
I'm also hitting the same issue as Jenny when trying to run cypress. I'm running on a clean repo with fresh node_modules. I'm investigating...

**Comment by mfrances17** [comment]
This took a bit of time to figure out but I believe the main issue is that cypress has not been added to package.json, it should be added under devDependencies, e.g.:
`  "cypress": "^6.3.0",`

I basically accomplished the same thing by running the following from within the repo:
`yarn add cypress --dev`

Once cypress has been installed to node_modules, you need to make sure that both admin consoles are running on ports 8180 and 8080 (as normal), and then make sure that you run the node_modules instance of cypress from within the tests subdirectory:

`<path-to-repo>/tests $> ../node_modules/.bin/cypress run`

Then it was able to execute the full test suite from my local repository (2 of 7 failed).

**Comment by jenny-s51** [comment]
Thank you for sharing your solution @mfrances17 - running `yarn add cypress --dev` worked for me

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Based on initial testing, I believe cypress should be added to the devDependencies of package.json, other than that, should be good to go.

**Comment by edewit** [comment]
@Aboullos I fixed the error that @mfrances17 and @jenny-s51 have in #336 by introducing workspaces

**Pull request closed without merging**
