### PR TITLE
initial move group dialog

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

Added move to dialog

## Brief Description

Now groups can be move to be a subgroup of another group

## Verification Steps

on a group row select "move to" then use the dialog to select a destination group for the selected subgroup

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Review by ssilvert — COMMENTED** [review]
It looks like this works fine except that the dialog doesn't dismiss.  I expect the dialog to go away and then I see the target group displayed.

Also, there isn't a test.

Given the title, I'm not sure if this is what you intended?

**Review by ssilvert — CHANGES_REQUESTED** [review]
There are some issues with the dialog.
- Needs a cancel button
- You can select your own group ("Move MyGroup to MyGroup")
- If you select a leaf group, all you selections are gone
- When navigating the groups, you can't go back to the parent.
- Search not working

Not sure if you meant to implement any or all of the above in this PR?

**Comment by edewit** [comment]
[The design](https://marvelapp.com/prototype/228971ig/screen/72210496) doesn't have a cancel button

**Comment by edewit** [comment]
> If you select a leaf group, all you selections are gone

You select a group by clicking it, the selection is not gone it's showing the sub groups of that group and there are none in the title you see the selected group.

**Comment by edewit** [comment]
image

**Review by jenny-s51 — CHANGES_REQUESTED** [review]
"Move groups" component looks great and seems to be working as expected! 

When I click on a group on the initial groups screen I see the URL changing, but it doesn't take me to the page that normally lists the subgroups

**Comment by edewit** [comment]
right @jenny-s51 that was fixed in #452 I'll rebase so that that will work here again as well

**Review by jenny-s51 — APPROVED** [review]

**Review by mfrances17 — APPROVED** [review]
Code LGTM, and worked as expected when tested. Nice job. Just need to fix those conflicts and you're good to go. :)

**Pull request merged**
