### PR TITLE
Use route functions for navigation in groups

### PR DESCRIPTION
**Pull request by jonkoops**

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Review by jenny-s51 — APPROVED** [review]
Routes are looking good @jonkoops ! Looks like the data-testid for searchGroups no longer exists on the dropdown item so maybe we can use a `.contains()` in the test instead

**Review by mfrances17 — CHANGES_REQUESTED** [review]
LGTM... just verify that the groups test that is failing is not due to the changes in this PR.

**Comment by jonkoops** [comment]
@mfrances17 The tests should pass properly now, could you take another look?

**Review by mfrances17 — APPROVED** [review]
LGTM... all group tests are passing - there are other test failures but they look completely unrelated. Approving and merging.

**Pull request merged**
