### PR TITLE
Update to Patternfly 4.171

### PR DESCRIPTION
**Pull request by jenny-s51**
## Motivation
Update to latest PF versions.

## Verification Steps
Tested new PF versions manually and ran cypress tests against them.

### CODE REVIEW

**Comment by jonkoops** [comment]
@jenny-s51 Looks like there are some issues with the build.

**Comment by jenny-s51** [comment]
@jonkoops The PF team is aware of our build errors and is currently working on making those related fixes! Will bump the version numbers once the PF team sends over the ones which resolve our issues 🙂

**Comment by jonkoops** [comment]
@jenny-s51 could you resolve the merge conflicts?

**Review by jonkoops — APPROVED** [review]
LGTM. Could be that some tests will fail due to changes on `main`, but we can merge this anyways.

**Comment by jenny-s51** [comment]
Sounds like a good plan - thank you @jonkoops !

**Pull request merged**
