### PR TITLE
changed to use the keycloak datatable

### PR DESCRIPTION
**Pull request by edewit**
so it will benifid from a general way tables work in the admin console

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
If I go to Client Scopes -> Mappers and click on a mapper, I get page not found.

Goes to:
` http://localhost:8080/master/client-scopes/58e38c4e-dd64-4a40-8735-1978d59a7b95/mappers`

Should be:
` http://localhost:8080/master/client-scopes/58e38c4e-dd64-4a40-8735-1978d59a7b95/mappers/04ae6c60-d166-46ae-8ed5-87409f067063`

**Comment by edewit** [comment]
@ssilvert I can't reproduce that, it still does that: https://github.com/keycloak/keycloak-admin-ui/pull/432/files#diff-63f259b70031ccc55825774e636f8e43c3c456256f73dd758726a8b393a18de4R101

**Comment by ssilvert** [comment]
> @ssilvert I can't reproduce that, it still does that: https://github.com/keycloak/keycloak-admin-ui/pull/432/files#diff-63f259b70031ccc55825774e636f8e43c3c456256f73dd758726a8b393a18de4R101

So today I'm getting a slightly different result, but it's still not working.   Try these steps and I'll ping you if you still can't reproduce.

1. Click on "Client scopes"
2. Click on a scope from the list
3. Click on Mappers tab
4. Click on a mapper

You will get a URL with `/settings/` in it like this `http://localhost:8080/master/client-scopes/58e38c4e-dd64-4a40-8735-1978d59a7b95/settings/479a4cd9-4ea9-458a-9bf5-4199a6030ce1`

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Similar to Stan, when I click one of the mappers in Client scope details, I get page not found... it's using 'settings' in the URI instead of 'mappers':

settings-uri

When i overwrite the URI w/ 'mappers', I get the mapper details:

mappers-uri

**Edit:**
Tested clicking the mapper to go to mapper details in other branches and it is working as expected, so something in this PR must break it.

**Pull request merged**
