### PR TITLE
Add RoutableTabs component for routed tabs

### PR DESCRIPTION
**Pull request by jonkoops**
## Motivation
Introduces a new `RoutableTabs` component that allows (nested) tabs to be routed by means of the path of a path. This component is intended as a replacement for `KeycloakTabs`, which requires too much configuration and does not support nested tabs properly.

This is required in order to facilitate returning to nested tabs after filling in a form related to that tab (for example #1823).

### CODE REVIEW

**Review by edewit — APPROVED** [review]
:+1: best we can do with the limits set by PF

**Review by jenny-s51 — CHANGES_REQUESTED** [review]
Great collaboration on this exciting update @jonkoops @edewit ! 

When I go to Realm Settings, I am unable to select any of the realm settings tabs at the moment -- the "General" tab always remains active when I click on a different tab.

**Comment by jonkoops** [comment]
@jenny-s51 I think you might be running an older version of PatternFly, can you run `npm install` and restart your dev server?

**Comment by jenny-s51** [comment]
Thanks @jonkoops ! The tabs are looking good and working as expected in `RealmSettings`. 

To test the nesting, I replaced the `Tabs` component that wrapped the Client Policies subtabs with `RoutableTabs`, then I added an optional `tab` param to `clientPoliciesParams` in `clientPoliciesRoute`. Then I passed `routableTab` into the `profiles` tab like this: 
```
                  {...routableTab({
                    to: toClientPolicies({
                      realm: realmName,
                      tab: "profiles",
                    }),
                    history,
                  })}
```

Is this how the component is expected to be used?

This is the result I'm getting, though we would expect that the tabs above should still be visible/selectable. How did you guys check that the nesting works as expected? I'd like to try the same on my end 🙂 

Screen Shot 2022-01-11 at 3 27 54 PM

**Comment by jonkoops** [comment]
@jenny-s51 We did some isolated testing on a new route to test out the nesting. Thinking about this specific overview, we might have to create more specific routes to ensure we're not accidentally rendering other routes. I'll see if I can get an implementation working.

**Comment by jonkoops** [comment]
@jenny-s51 I've pushed some work to make sure nested tabs remain active, looks like my initial code was not properly optimized for it. 

@edewit could you also review this new code?

**Review by edewit — APPROVED** [review]
:+1:

**Review by jenny-s51 — APPROVED** [review]
Looking good @jonkoops ! I added a `subTab` attribute to the `toRealmSettings` route, e.g. 
```
             {...routableTab({
                to: toRealmSettings({
                  realm: realmName,
                  tab: "clientPolicies",
                  subTab: "policies",
                }),
                history,
              })}
```

Thank you for looking into the nested tabs issue - the test case I used initially was still not showing the tabs, but when done this way, the behavior works as expected. 👍

**Comment by jonkoops** [comment]
Nice, I am happy to hear it's working. I still see a couple of rough edges in my own testing with nested tabs, but I think they could be resolved. I'll merge this PR after the tests pass and then take another look.

**Pull request merged**
