### PR TITLE
Upgrade to PF 4.194

### PR DESCRIPTION
**Pull request by jenny-s51**
Upgrade to newly released PF versions (release 06.2022)

### CODE REVIEW

**Comment by jonkoops** [comment]
@jenny-s51 can we close this PR or do you still need it?

**Comment by jenny-s51** [comment]
I've rebased and pushed - these are the new PF versions which have been released - leaving open for convenience if you want to merge these #s in

**Review by jonkoops — APPROVED** [review]
Clicked around a bit and all looks well.

**Comment by jonkoops** [comment]
Thanks for this Jenny :rocket:

**Pull request merged**
