### PR TITLE
added download dialog to client actions

### PR DESCRIPTION
**Pull request by edewit**
[marvel](https://marvelapp.com/prototype/908c3c3/screen/72040453)

### CODE REVIEW

**Comment by ssilvert** [comment]
"Download adapter" bleeds off the screen:
menu-bleed

**Review by ssilvert — CHANGES_REQUESTED** [review]
Other than the bleed issue, this looks great!

**Comment by edewit** [comment]
Right I did see that of course, thought we could add it as an issue, because we need some custom css I think to fix that @srambach ?

**Comment by srambach** [comment]
@edewit I think you can just add `position={DropdownPosition.right}` to your dropdown

**Comment by edewit** [comment]
@srambach it's a `<Select>` it only has `direction="up | down"`

**Comment by srambach** [comment]
Hmm. Semantically I would expect that to be a dropdown. Typically a select should be used when the element needs to hold a value, whereas a dropdown is preferred for an action menu. I did not notice that before; I think it's worth an issue to swap that out and then the alignment can easily be fixed as well.

**Comment by edewit** [comment]
It's in your ViewHeader... so...

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
I'm going to go ahead and merge this.  Created issue so @edewit and/or @srambach can address the "bleed" issue.  #171

**Comment by srambach** [comment]
> It's in your ViewHeader... so...

Yeah, I know 🤦 I can take #171 to switch it if you want @edewit

**Comment by edewit** [comment]
be my guest...

**Pull request merged**
