### PR TITLE
new client wizard uxd review

### PR DESCRIPTION
**Pull request by edewit**
changed to be progressive added help to type
and made `openid-connect` the default

fixes: #446

### CODE REVIEW

**Review by mfrances17 — APPROVED** [review]
LGTM, worked great and i like the progressive wizard style better. 

One thing I noticed, I'm not fond of the 'Save' label for the button when you are first creating something. It should probably be "Create' (to match the wizard name 'Create client') or similar.

**Comment by ssilvert** [comment]
> One thing I noticed, I'm not fond of the 'Save' label for the button when you are first creating something. It should probably be "Create' (to match the wizard name 'Create client') or similar.
> 
@mfrances17 I agree.  Please create an issue and assign to @yih-wang to get her opinion.

**Comment by ssilvert** [comment]
@xianli123 Please review.

**Comment by xianli123** [comment]
Thanks. Looks good to me. Another little detail: It's better to center the tags and the switch.

**Comment by xianli123** [comment]
Hi @edewit We can add a question mark after the Client authentication and Authorization respectively.


In addition, if we go back to Step 1 from the step2, we'll see that the items that were already filled in have been deleted, which is a bit strange. Can we keep the completed items as they are?

**Comment by xianli123** [comment]
Hi @edewit, there are some details of the OIDC capability configs that need to be fine-tuned in both the Creation page and Settings page.

1. Terminology correction
Please change **_Direct access_**  to **_Direct access grants_**, and change **_Service account roles_** to **_Service accounts_**.
Screen Shot 2021-04-23 at 2 08 31 PM


2. Relationships between Client authentication, Authorization, and Service accounts.
- `Authentication` is **OFF**:
Authorization is OFF and can’t be edited. Service accounts can be edited.
- `Authentication` is **ON**:
Authorization and Service accounts can be edited. If the Authorization is ON, Service accounts will be selected by default and can’t be edited. If the Authorization is OFF, Service accounts can be edited.

If you want to delve further into the interaction details, please refer to the prototype. https://5lvn0v.axshare.com/#id=ol9a55&p=usability_testing&c=1

**Pull request merged**
