### PR TITLE
Kerberos and LDAP settings: Change hour and minute format to match old admin console UI

### PR DESCRIPTION
**Pull request by mfrances17**
## Motivation
https://github.com/keycloak/keycloak-admin-ui/issues/322

## Brief Description
Fixes a few issues in the Cache section of both the Kerberos and LDAP settings pages:

- Fixes an issue in which the format of the minutes and hours drop-downs did not match the old admin console UI. Request was that we need to format them like the old console, with leading 0s when applicable. In the new console, the hour numbering now goes from 00-23 (as in the old console), instead of 1-24. In the new console, the minute numbering now goes from 00-59 (as in the old console), instead of 1-60.

- Fixes an issue in which the max lifespan fields were labeled and tagged as required (*). These fields accept blank values so removed the required tags.
 
- Fixed an issue with the days of the week sometimes not retrieving correctly from the server, and were resetting to Sunday (default). 

## Verification Steps
1. From the User Federation screen, click a Kerberos card to open settings.
2. In the Cache Settings section, select EVICT_WEEKLY or EVICT_DAILY from the Cache policy dropdown.
3. Verify that the hour and minute dropdowns list the correct values as noted above.
4. Verify that you can read/write these values correctly, preferably by checking them in the old console UI.
5. Select EVICT_WEEKLY and verify that you can read/write all days of the week correctly.
6. Select MAX_LIFESPAN from the Cache policy dropdown and verify that the Max lifespan field is no longer showing as required.
7. Repeat steps 1-6 for LDAP user federation settings. 

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes
None

### CODE REVIEW

**Review by jenny-s51 — CHANGES_REQUESTED** [review]
Nice work @mfrances17 ! 

The hour and minute formats are updating successfully for EVICT_DAILY and EVICT_WEEKLY.

I'm getting a 500 error when I select "EVICT_WEEKLY" and immediately try saving. It goes away when I select a day from the dropdown, so I'm guessing this has to do with the `defaultValue`. 

Otherwise this looks good and matches the old console 👍

**Review by edewit — CHANGES_REQUESTED** [review]
I don't know the full story, but couldn't we changed it to displaying 1 - 24 but using the values 0 - 23? Also isn't this more a local issue? Wouldn't it be more user friendly to show "AM" "PM" labels for English?

I also get a 500 for weekly it's because it may be because evict day is saved as: `evictionDay: [["Sunday"]]`

**Comment by mfrances17** [comment]
@jenny-s51 @edewit fixed the DoW default value issue, the 500 should be fixed if no value is chosen from the drop-down

**Comment by mfrances17** [comment]
> I don't know the full story, but couldn't we changed it to displaying 1 - 24 but using the values 0 - 23? Also isn't this more a local issue? Wouldn't it be more user friendly to show "AM" "PM" labels for English?
> 
> I also get a 500 for weekly it's because it may be because evict day is saved as: `evictionDay: [["Sunday"]]`

The default day of week value is fixed... the other changes were made to have it work like the old console. Maybe treat the option to do local time formatting as a feature request?

**Review by ssilvert — CHANGES_REQUESTED** [review]
Looks like a lot of stuff is repeated in KerberosSettingsCache and LdapSettingsCache?  Can we factor out some common components?

**Review by jenny-s51 — APPROVED** [review]
EVICT_WEEKLY working as expected now 👍

**Comment by mfrances17** [comment]
> Looks like a lot of stuff is repeated in KerberosSettingsCache and LdapSettingsCache? Can we factor out some common components?

@ssilvert indeed! this was bugging me as well. however, instead of factoring out several components, i instead created one SettingsCache component that is shared by both LDAP and Kerberos, instead of two separate cache components that were doing the same thing.

**Comment by mfrances17** [comment]
Unsure why FormAccess test is failing... I had already updated the snap prior to the failure(s). Even tried re-running the test on the server.

**Comment by ssilvert** [comment]
> Unsure why FormAccess test is failing... I had already updated the snap prior to the failure(s). Even tried re-running the test on the server. The tests all pass when run locally.

Maybe a dumb question, but are you sure that updated snapshots are updated in your commits?

**Comment by mfrances17** [comment]
> > Unsure why FormAccess test is failing... I had already updated the snap prior to the failure(s). Even tried re-running the test on the server. The tests all pass when run locally.
> 
> Maybe a dumb question, but are you sure that updated snapshots are updated in your commits?

https://github.com/keycloak/keycloak-admin-ui/pull/353/commits/073e3615015aa90815e709f34f13a088966d4d08

**Comment by ssilvert** [comment]
> > > Unsure why FormAccess test is failing... I had already updated the snap prior to the failure(s). Even tried re-running the test on the server. The tests all pass when run locally.
> > 
> > 
> > Maybe a dumb question, but are you sure that updated snapshots are updated in your commits?
> 
> [073e361](https://github.com/keycloak/keycloak-admin-ui/commit/073e3615015aa90815e709f34f13a088966d4d08)

I just ran the tests with your code and got a failure.

**Comment by ssilvert** [comment]
> > > > Unsure why FormAccess test is failing... I had already updated the snap prior to the failure(s). Even tried re-running the test on the server. The tests all pass when run locally.
> > > 
> > > 
> > > Maybe a dumb question, but are you sure that updated snapshots are updated in your commits?
> > 
> > 
> > [073e361](https://github.com/keycloak/keycloak-admin-ui/commit/073e3615015aa90815e709f34f13a088966d4d08)
> 
> I just ran the tests with your code and got a failure.

` FAIL  src/components/form-access/__tests__/FormAccess.test.tsx (20.811s)
  <FormAccess />
    × render normal form (389ms)
    √ render form disabled for test realm (40ms)`

**Comment by mfrances17** [comment]
> > > > > Unsure why FormAccess test is failing... I had already updated the snap prior to the failure(s). Even tried re-running the test on the server. The tests all pass when run locally.
> > > > 
> > > > 
> > > > Maybe a dumb question, but are you sure that updated snapshots are updated in your commits?
> > > 
> > > 
> > > [073e361](https://github.com/keycloak/keycloak-admin-ui/commit/073e3615015aa90815e709f34f13a088966d4d08)
> > 
> > 
> > I just ran the tests with your code and got a failure.
> 
> ` FAIL src/components/form-access/__tests__/FormAccess.test.tsx (20.811s) <FormAccess /> × render normal form (389ms) √ render form disabled for test realm (40ms)`

Yep, that's the same as the server. I'm still investigating why it's different on my local build. Hopefully have a solution soon.

**Comment by mfrances17** [comment]
> > > > > > Unsure why FormAccess test is failing... I had already updated the snap prior to the failure(s). Even tried re-running the test on the server. The tests all pass when run locally.
> > > > > 
> > > > > 
> > > > > Maybe a dumb question, but are you sure that updated snapshots are updated in your commits?
> > > > 
> > > > 
> > > > [073e361](https://github.com/keycloak/keycloak-admin-ui/commit/073e3615015aa90815e709f34f13a088966d4d08)
> > > 
> > > 
> > > I just ran the tests with your code and got a failure.
> > 
> > 
> > ` FAIL src/components/form-access/__tests__/FormAccess.test.tsx (20.811s) <FormAccess /> × render normal form (389ms) √ render form disabled for test realm (40ms)`
> 
> Yep, that's the same as the server. I'm still investigating why it's different on my local build. Hopefully have a solution soon.

@ssilvert when all else fails, wipe node_modules and rebuild... got it to fail and fixed the failing test.

**Review by ssilvert — APPROVED** [review]
LGTM

**Pull request merged**
