### PR TITLE
Replace Snowpack with Vite

### PR DESCRIPTION
**Pull request by jonkoops**
Replaces Snowpack with Vite as it is no longer [actively maintained](https://github.com/FredKSchott/snowpack/issues/3491).

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Review by edewit — COMMENTED** [review]
No more rhsso theme?

**Review by edewit — APPROVED** [review]

**Comment by jonkoops** [comment]
> No more rhsso theme?

Yeah, we never agreed on this with the productization team so we need to sit down with them and work this out.

**Review by agagancarczyk — APPROVED** [review]

**Comment by agagancarczyk** [comment]
@jonkoops all looks good except for the issue with "the context hierarchy" when you make a change on some files i.e Dashboard.tsx, which we have already discussed. I can review this again.

**Comment by jonkoops** [comment]
> all looks good except for the issue with "the context hierarchy" when you make a change on some files

Looking into that now, but should not be a blocker for merging this PR I think. Worst case scenario we have to do some manual refreshing during development every once and a while.

**Pull request merged**
