### PR TITLE
can't move groups to the root level

### PR DESCRIPTION
**Pull request by edewit**
disabled "Move" button on root level

fixing: #476

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
Looks like this does fix an issue, but it's not what I meant.  I should have been more clear.

Say I have these groups:
/A
/A/B

I should be able to move B to the root so then I would have:
/A
/B

Also, I noticed that when you delete a group, the screen is not refreshed.

**Comment by edewit** [comment]
Right that is why I disabled the `Move` button as you can't move group `B` to `/` as there is no API to do that you can only move group `B` to be a subgroup of another group

**Comment by ssilvert** [comment]
> Right that is why I disabled the `Move` button as you can't move group `B` to `/` as there is no API to do that you can only move group `B` to be a subgroup of another group

I can do it in the old console.  If I have A/B I just click on B and say "cut".  Then I highlight "Groups", which is the root.  Then click on "paste".  Looks like it uses a different API when you want to move it to the root.

**Review by ssilvert — CHANGES_REQUESTED** [review]
This looks good.  Just need a test case for it.

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
