### PR TITLE
added client scope details screen

### PR DESCRIPTION
**Pull request by edewit**
[marvel app](https://marvelapp.com/prototype/5cf7cfd/screen/72040359)

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
`Include in token scope` is missing from this form.

Also, `type` is missing.

**Comment by edewit** [comment]
@ssilvert don't know why I did it, but I'm rendering `type` only when you re creating a client-scope not when editing. Changed it back to always rending it.

**Comment by edewit** [comment]
ahh found it here: https://marvelapp.com/prototype/5cf7cfd/screen/72040359 seems I need a different way to know when not to render what.

**Comment by ssilvert** [comment]
@edewit Doesn't matter if we address this here or later, but throughout Client scopes, `GUI order` should be called `Display order`.  This is something we changed in design discussions, but some of the wireframes still don't reflect that decision.

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
