### PR TITLE
fixing comment on issue:

### PR DESCRIPTION
**Pull request by edewit**
https://github.com/keycloak/keycloak-admin-ui/issues/428#issuecomment-818504696

### CODE REVIEW

**Review by mfrances17 — CHANGES_REQUESTED** [review]
i'm not sure this meets what the issue had requested... it looks like there is a gap larger (height) than 24px between the tabs and the client authenticator section. also, noticed that the separator above client secret is not going all the way across anymore, probably not intended:

credentials-tab

**Comment by edewit** [comment]
@mfrances17 with this padding on the top it's the same as the settings tab. If we make the padding on the top different on this page then others need to change too? @xianli123 ?

Any ideas on how to make the separator go the entire width?

**Comment by xianli123** [comment]
hi @edewit @mfrances17 I've added some measurements, as the picture shows below. 

Client ID   Secret - 3 Copy

The padding on the top should be 24px. The same thing happens to the Settings page.
It’s better to let the separator go the entire width. WDYT?

**Comment by xianli123** [comment]
This gap is still a bit wide, and it's not the same height as the Settings page. Can you fine-tune it? Thanks.
Screen Shot 2021-04-20 at 9 03 36 PM

**Comment by edewit** [comment]
@xianli123 it's the same as on the side right, that was the idea e.g. x == y = 24px so I don't know what else to make of it
image

**Review by ssilvert — APPROVED** [review]
I'm going to go ahead and merge.  We can fine tune this later when we have more time.

**Comment by xianli123** [comment]
> @xianli123 it's the same as on the side right, that was the idea e.g. x == y = 24px so I don't know what else to make of it
> image

OK, I may make some mistakes. I will review the new UI, and if there are some updates, I will let you know.

**Pull request merged**
