### PR TITLE
change to TextInput when editing 

### PR DESCRIPTION
**Pull request by edewit**
Because keycloak doesn't store the password as clear text and returns the password as '***' it doesn't make sense to reveal the text

fixes: #971

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Since this is a UX review ticker I think that someone from the UXD team will have to take a look at it before merging. @xianli123 @yih-wang could you take a look at it.

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Seems like it would make more sense to add this change to the PasswordInput component itself, instead of burying a new component within LDAP settings... what do you think?

**Comment by yih-wang** [comment]
LGTM

**Comment by edewit** [comment]
@mfrances17 all I do is change the password input field out for a normal text field when it's in edit mode. Are you suggesting to add an edit mode property to the `PasswordInput` field itself?

**Comment by mfrances17** [comment]
@edewit yeah i figured since we've already create a custom password component, it could just be one more prop we add to it. another quicker but less desirable option would be to just lift the new PasswordComponent out of ldap settings and define it as a separate keycloak component in \Components. but then we'd have two specialized keycloak password components. just a suggestion.

**Comment by edewit** [comment]
@mfrances17 done

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
