### PR TITLE
removed bookmarable sub tab

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

the bookmarkable subtab made the navigation between tabs strange so removed that feature

## Brief Description

fixes: #404

## Verification Steps

See issue

### CODE REVIEW

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Changes look good, and navigating from subtabs to normal tabs now works as expected, and the routes are no longer messed up.

The client cypress test (at _Advanced tab test_) and client scopes cypress test (at _Client scope CRUD test_) are both failing, it looks as though a result of these changes

**Comment by mfrances17** [comment]
@edewit Are these tests passing for you? They are still failing on my system with your latest code changes.

**Comment by edewit** [comment]
they are green for me, also on the CI

**Review by mfrances17 — APPROVED** [review]
Ok, approving

**Pull request merged**
