### PR TITLE
fixing issue

### PR DESCRIPTION
**Pull request by edewit**
fixes: #667

### CODE REVIEW

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Is this meant as a partial fix to #667? If so, maybe it should be renamed. I don't see fixes for 1 (question mark/help), 2 (rename tab), or 4 (add kabobs), I only see a fix for 3 which is to deal with checkboxes and inherited roles, which works in my testing.

Let me know if only number 3 was supposed to be covered in this review, and i'll approve. Also, one thing i'm not sure can be changed - if you select the select all rows checkbox aka the one to the left of the Name column header, the checkboxes for disabled roles (the inherited roles) are checked. But i think this is a visual thing only as i had 6 checked but the count in the confirm modal was 5. It may just be an unfortunate visual anomaly, not sure if it can be easily fixed or not, or if it's worth fixing because again i don't think the selection is actually happening.

**Comment by edewit** [comment]
ehh... #708 is the number of this PR it fixes #667

**Comment by mfrances17** [comment]
Sorry that was a typo on my part... I was referencing issue https://github.com/keycloak/keycloak-admin-ui/issues/667. I'll edit the original.

**Comment by edewit** [comment]
Added help on Enable Switch: 
image

**Comment by edewit** [comment]
@mfrances17 this PR now fixes all of the issues in #667

**Comment by mfrances17** [comment]
@edewit looks good, all issues are addressed. great job. i'm approving as-is. for the future we should think about creating a keycloak component that has the enabled and question mark help built-in, and also the ? should be closer to the Enabled text since it almost looks like it belongs with the Action menu since it is closer to that, and it should be a shade of gray like the other help toggles instead of black. But i think those should be handled as separate issues.

**Pull request merged**
