### PR TITLE
Change to using quarkus features option and add fine grained auth

### PR DESCRIPTION
**Pull request by ssilvert**
## Motivation
Make use of keycloak-quarkus features option and add fine grained authorization.  This is now preferred to using the java system properties.

## Brief Description
Based on https://www.keycloak.org/server/features

## Verification Steps
I am unable to run the start.mjs file on my box, so I need someone else to verify that this works.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

**Review by jonkoops — CHANGES_REQUESTED** [review]
Could you also update this for the other places in the project where these flags are mentioned?

**Comment by ssilvert** [comment]
> Could you also update this for the other places in the project where these flags are mentioned?

I only found one other place, which was cypress.yml.  Again, I will need your help with testing.

**Comment by jonkoops** [comment]
@ssilvert There is another [reference](https://github.com/keycloak/keycloak-admin-ui/blob/439212c4b597b7d4ed7555d2912dc3df316199b2/keycloak-theme/README.md#to-run) in the readme of `keycloak-theme`.

**Comment by ssilvert** [comment]
> Changes seem to work 👌 Still need an update of the reference in the readme of `keycloak-theme`.

@jonkoops  Is that document still accurate overall?  Is it still needed?

**Comment by jonkoops** [comment]
@ssilvert I am changing it up in https://github.com/keycloak/keycloak-admin-ui/pull/2259 so let's omit it from this PR.

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
