### PR TITLE
initial version of the sessions section

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

[marvel app](https://marvelapp.com/prototype/5e9e849/screen/73427080)

## Verification Steps

Go to sessions

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Comment by edewit** [comment]
this PR needs the newer admin client that will be introduced by #259

**Review by mfrances17 — COMMENTED** [review]
code looks great. i'm having trouble testing, i think keycloak-admin 1.14.4 is not available yet? it's not recognizing sessions off of keyclock-admin, and when i look in the file i don't see it defined. i'm assuming that's what's in the latest version... is there a way i can test? the latest package.json pulls in 1.14.4 but 1.14.2 still seems to be installed locally.

**Comment by edewit** [comment]
https://www.npmjs.com/package/keycloak-admin the latest version is 1.14.4 and the yarn.lock file seems to have the right hash. Maybe you need to update the `node_modules` manually?

**Review by mfrances17 — APPROVED** [review]
LGTM, was able to pull down fresh repo, UI looked great

**Pull request merged**
