### PR TITLE
Process UXD review for Client Scopes

### LINKED ISSUE #1017: [UX Review] Some fine-tuning of Client scopes
Hi @edewit ，there are some fine-tuning of client scopes, please check and fix them.

> Screen Shot 2021-08-18 at 2 25 03 PM
All the client scopes should be in alphabetical order. We can put the "Description" column after the "Display order". In other words, the order should be Name > Type > Protocol > Display order > Description.

> Screen Shot 2021-08-18 at 2 26 25 PM
In the client scope's detailed page, the minimum value of the "Display order" should be 0. The same thing happens to the creation page.

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #1017

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Comment by jonkoops** [comment]
@xianli123 Could you tell me if this addresses all you comments?

**Review by mfrances17 — DISMISSED** [review]
Code looks good. When testing, scopes were listed in alphabetical order, newly created ones were also in correct alphabetical order, and the priority starts at 0 and doesn't go negative. 

The only thing I'm seeing is that there was a request to change the column order as part of that UXD review issue, and it doesn't look like it was implemented. The suggestion was to use this order:  **Name > Type > Protocol > Display order > Description** but i'm still seeing it as: **Name > Description > Type > Protocol > Display order**.

**Comment by xianli123** [comment]
As @mfrances17 mentioned that the order should be **Name > Type > Protocol > Display order > Description**. @jonkoops Could you please change the order? And we can change the "Type" to "Assigned type" to be consistent with the old console.
Screen Shot 2021-08-20 at 11 40 53 AM

In addition, we discussed the client scopes functionality and we want to unify some things in Client scopes page(in the nav bar) and the Client scopes-Setup page(in the client details page). Therefore, I am going to create a new issue to record the updates and the new issue will not affect our current work.

**Comment by xianli123** [comment]
@jonkoops @mfrances17 I created a new issue for unifying the toolbar of the client scopes list. Please check it. [[UX Review] Update the toolbar of Client scopes list](https://github.com/keycloak/keycloak-admin-ui/issues/1027)

**Comment by jonkoops** [comment]
@mfrances17 @xianli123 I've added the aforementioned changes to the columns, can you take another look?

**Comment by xianli123** [comment]
Thanks. I've checked it and it looks good to me.

**Pull request merged**
