### PR TITLE
Add help text to the realm localization fields

### LINKED ISSUE #686: [UX Review] Localization help text
Hi @andymunro, please help to create help text for the following three fields. You can refer to the "Theme" tab in the "Realm settings" page with the old console. In addition, there are some links for your reference. Thanks.

UI design: https://marvelapp.com/prototype/56d9606/screen/76458137
Documentation: https://www.keycloak.org/docs/latest/server_admin/index.html#internationalization
Rough idea: https://docs.google.com/document/d/1GCAmHJgVaSyRyqjAX2nzy334CIzW-RbB75q5-Qr6QyI/edit?usp=sharing

> Screen Shot 2021-06-08 at 8 35 21 PM

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #686

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Review by jenny-s51 — APPROVED** [review]
LGTM 👍

**Comment by xianli123** [comment]
@jonkoops The help text looks good to me. But the page looks a bit weird. If the Internationalization switch is OFF, the settings below just show the tags. Should I create a new issue to track this error?
Screen Shot 2021-09-30 at 3 32 55 PM
e

**Review by xianli123 — APPROVED** [review]
Looks good to me. Thanks.

**Comment by jonkoops** [comment]
@xianli123 Yeah you can create an issue for that so we can pick it up separately. I also thought this behavior was very strange, I would have expected the labels to disappear as well, or to see the fields but in a disabled state.

**Pull request merged**
