### PR TITLE
Use new admin client with seperated Keycloak JS

### PR DESCRIPTION
**Pull request by jonkoops**
Updates the admin client to the latest version and splits out Keycloak JS as per https://github.com/keycloak/keycloak-nodejs-admin-client/pull/511.

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
I'm fine with the changes, but tests are failing.  Hard to know if the changes actually caused the failures.  I don't seem to be able to re-run the tests.  Also, another PR was just submitted with all tests passing.

**Comment by jonkoops** [comment]
I'm re-starting the tests to see if this fixes the issue, these tests are known to fail from time to time.

> Also, another PR was just submitted with all tests passing.

If you are talking about #2960 it looks like the tests for that PR never ran for some reason.

**Comment by ssilvert** [comment]
Yea, I was talking about #2960.  Hmm.

**Review by edewit — APPROVED** [review]

**Comment by edewit** [comment]
@jonkoops seems there is a `/` missing from the `keycloak.authServerUrl`

**Comment by jonkoops** [comment]
Ahhh, yes. Good catch @edewit. I've pushed a fix, let's see what that does to the tests.

**Review by edewit — APPROVED** [review]
:+1:

**Review by ssilvert — APPROVED** [review]

**Review by agagancarczyk — APPROVED** [review]

**Pull request merged**
