### PR TITLE
changed `asyncStateFetch` to be it's own hook

### PR DESCRIPTION
**Pull request by edewit**
it now cancels pending requests making sure we
don't leak memory + it makes for an nicer looking API

### CODE REVIEW

**Comment by ssilvert** [comment]
@edewit Please resolve conflicts.

**Comment by ssilvert** [comment]
@edewit Please re-run tests after fixing conflicts.  I was kicking off tests for all existing PR's but didn't do it for this one.

**Comment by ssilvert** [comment]
@edewit When I run this I get Uncaught SyntaxError: The requested module '../context/auth/AdminClient.js' does not provide an export named 'asyncStateFetch'

This is in UserFederationLdapSettings

**Comment by edewit** [comment]
@ssilvert right fixed merge error

**Review by mfrances17 — APPROVED** [review]
Code LGTM, tested great. Just fix those new merge conflicts. :)

**Comment by edewit** [comment]
merge conflicts fixed @mfrances17

**Pull request merged**
