### PR TITLE
added export and delete

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
Please translate all the visible strings.
Need a nicer message after delete action.  See old admin console for example.

**Comment by ssilvert** [comment]
Home URL is messed up:
HomeURL

**Comment by edewit** [comment]
the double url you only get when there was a hot reload

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
@edewit Please address format check.

**Pull request merged**
