### PR TITLE
Ask for confirmation before unlinking users

### LINKED ISSUE #1395: User Federation LDAP: `Remove imported users` modal has wrong text
When you select action `Remove imported users`, the text in the modal says,
`Do you really want to remove all imported users? The option "Unlink users" makes sense just for the Edit Mode "Unsynced" and there should be a warning that "unlinked" users without the password in the Keycloak database won't be able to authenticate.`

I believe that this text came from the wireframe is intended as instructions for the developer.

@andymunro @yih-wang We need more specific text for the modal(s).

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #1395

### CODE REVIEW

**Review by agagancarczyk — APPROVED** [review]
LGTM @jonkoops , but could you please add a cypress test for this confirmation as part of this or next PR?

**Comment by jonkoops** [comment]
Working on the tests now, I'll see if I can make it part of this PR. Otherwise I'll open up a new one.

**Comment by jonkoops** [comment]
@xianli123 @yih-wang Could you take a look to see if this matches the expectation of UXD as well and leave a review? Thanks in advance.

**Review by mfrances17 — CHANGES_REQUESTED** [review]
If `Edit mode` is set to `READ_ONLY` or `WRITABLE`, and I change it to `UNSYNCED`, the `Unlink users` command is still not selectable, even after a save. You need to exit the settings and return in order for the `Unlink users` command to be selectable. Is this the desired behavior?

**Comment by xianli123** [comment]
Hi @jonkoops sorry for the late reply. That looks good to me. @yih-wang WDYT?

**Comment by xianli123** [comment]
hi @jonkoops , sorry for the late reply. What happened to @mfrances17 that happened to me. I think it's a bug.

**Comment by xianli123** [comment]
In the UI, if I change the **Edit mode** to "Unsynced" and save the change, the "Unlink users" is still disabled. When you leave this page and re-enter, "Unlink User" will be enabled. But at that moment, the "Unlink users" is always enabled whatever **Edit mode** is. I guess it's a bug. Could you please fix it? Thanks! @jonkoops

**Comment by jonkoops** [comment]
I created an issue to write some tests for this at a later point in #1477

**Comment by jonkoops** [comment]
@xianli123 @mfrances17 Thanks for testing this, I have added some code to refresh the form state with the latest data after saving, can you take another look?

**Review by xianli123 — COMMENTED** [review]
Looks good to me. Thanks.

**Comment by xianli123** [comment]
@jonkoops This pr has fixed the issue of the **Unlink users**. It looks good to me. 

But I found another general issue and created a new one to describe it. FYI: https://github.com/keycloak/keycloak-admin-ui/issues/1496. The same thing happened to User federation part, please take a look. Thanks.

**Review by mfrances17 — APPROVED** [review]
The issue I found in which you needed to exit the settings and return in order for the `Unlink users` command to be selectable is now fixed. Great job, @jonkoops. Approving and merging.

**Pull request merged**
