### PR TITLE
introduced "/" for keycloak.json

### PR DESCRIPTION
**Pull request by edewit**
fixes: #165

### CODE REVIEW

**Review by ssilvert — COMMENTED** [review]
@edewit We need to think about this some more.  This solution will only work for the master realm.

**Comment by edewit** [comment]
I don't know why you say that, but I'll take your word for it.

**Comment by edewit** [comment]
For me it works on every realm, this just solves the 404 you get for the `keycloak.json` when on a details page and pressing refresh

**Comment by ssilvert** [comment]
Hmm.  OK.  I'll merge it then.  Sounds like this is at least a step forward.

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
