### PR TITLE
added function to refresh the dataloader data

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Review by jenny-s51 — APPROVED** [review]
LGTM, clients list gets updated appropriately once a client is deleted. just fix merge conflict

**Comment by ssilvert** [comment]
@edewit Looks like this one is holding up @jenny-s51?  

Will this be superseded by the nodejs admin client work?

**Review by jenny-s51 — COMMENTED** [review]
just tested on my branch - the `refresh()` doesn't seem to work for me when I delete a realm role, and the state still will not update until I manually refresh

**Comment by edewit** [comment]
@ssilvert It's not holding up anything and it's useful also when the new admin client is there

**Pull request merged**
