### PR TITLE
default value and required field for generate keys

### PR DESCRIPTION
**Pull request by edewit**
fixes: #1715

### CODE REVIEW

**Review by mfrances17 — DISMISSED** [review]
Code looks good, tested well. Only one comment - Key alias now defaults to client name by default as requested in the issue, but not when you choose to import. Shouldn't that be the case there as well?

**Review by jonkoops — CHANGES_REQUESTED** [review]
Changes look good, but some of the tests are failing. Can you take a look @edewit?

**Comment by edewit** [comment]
> Code looks good, tested well. Only one comment - Key alias now defaults to client name by default as requested in the issue, but not when you choose to import. Shouldn't that be the case there as well?

I don't know @xianli123, what about this case?

**Review by jonkoops — APPROVED** [review]

**Comment by xianli123** [comment]
Hi @edewit @jonkoops @mfrances17 , the default value of "Key alias" should be the client name when users generate the new key. Key alias will be an input field when a user imports a certificate.

**Pull request merged**
