### PR TITLE
Client "Advanced" tab

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

Adds the "Advanced" tab to the clients section [marvel](https://marvelapp.com/prototype/9a93gef/screen/75845552)

## Brief Description

Advanced tab contains things you don't need often like clustering and revocation

## Verification Steps

Open a specific client and navigate to the advanced tab.

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Comment by mfrances17** [comment]
Attempted to load the changes in your repo two days in a row, no success. Today I wiped everything clean and rebuilt from scratch, still getting the same 404 back from the server:
`[snowpack] [404] /_dist_/clients/Advanced/index.js`

**Comment by edewit** [comment]
don't know how to reproduce it just did a clean as well:
```bash
$> git clean -dfX .
```
And then run everything new and got:

```
snowpack

  http://localhost:8080 • http://192.168.0.32:8080
  Server started.

▼ Console

[snowpack] ! updating dependencies...
[snowpack] ! installing dependencies…
[snowpack] Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[snowpack] Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[snowpack] Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[snowpack] Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[snowpack] Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[snowpack] Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[snowpack] Non-existent export 'DropdownItemProps' is imported from node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/components/Dropdown/DropdownItem.js
[snowpack] Non-existent export 'OUIAProps' is imported from node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/helpers/ouia.js
[snowpack] ✔ install complete [37.85s]
[snowpack] 
  ⦿ web_modules/                                                size       gzip       brotli   
    ├─ @patternfly/react-core.js                                737.5 KB   143.7 KB   108.56 KB  
    ├─ @patternfly/react-icons.js                               1629 KB    532.81 KB  428.49 KB  
    ├─ @patternfly/react-table.js                               317.48 KB  65.59 KB   53.9 KB    
    ├─ @storybook/addon-actions.js                              37.05 KB   9.79 KB    8.37 KB    
    ├─ @storybook/react.js                                      259.02 KB  65.86 KB   53.49 KB   
    ├─ file-saver.js                                            2.67 KB    1.28 KB    1.1 KB     
    ├─ i18next.js                                               77.3 KB    16.35 KB   14.08 KB   
    ├─ keycloak-admin.js                                        252.72 KB  44.03 KB   35.86 KB   
    ├─ keycloak-admin/lib/defs/adminEventRepresentation.js      0.38 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/clientRepresentation.js          0.36 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/clientScopeRepresentation.js     0.38 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/componentRepresentation.js       0.37 KB    0.22 KB    0.16 KB    
    ├─ keycloak-admin/lib/defs/configPropertyRepresentation.js  0.39 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/credentialRepresentation.js      0.38 KB    0.22 KB    0.18 KB    
    ├─ keycloak-admin/lib/defs/eventRepresentation.js           0.36 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/globalRequestResult.js           0.36 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/groupRepresentation.js           0.36 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/protocolMapperRepresentation.js  0.39 KB    0.22 KB    0.18 KB    
    ├─ keycloak-admin/lib/defs/realmRepresentation.js           0.36 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/roleRepresentation.js            0.35 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/serverInfoRepesentation.js       0.37 KB    0.22 KB    0.18 KB    
    ├─ keycloak-admin/lib/defs/userRepresentation.js            0.35 KB    0.21 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/userSessionRepresentation.js     0.38 KB    0.22 KB    0.17 KB    
    ├─ keycloak-admin/lib/defs/whoAmIRepresentation.js          0.36 KB    0.22 KB    0.17 KB    
    ├─ lodash.js                                                542.26 KB  96.61 KB   73.93 KB   
    ├─ moment.js                                                173.82 KB  36.52 KB   30.32 KB   
    ├─ react-dom.js                                             1.05 KB    0.37 KB    0.33 KB    
    ├─ react-hook-form.js                                       76.39 KB   15.13 KB   13.21 KB   
    ├─ react-i18next.js                                         36.11 KB   8.72 KB    7.73 KB    
    ├─ react-router-dom.js                                      9.85 KB    2.76 KB    2.4 KB     
    ├─ react.js                                                 1.62 KB    0.53 KB    0.47 KB    
    └─ use-react-router-breadcrumbs.js                          9.63 KB    3.44 KB    2.86 KB    
  ⦿ web_modules/common/ (Shared)
    ├─ _baseIsEqual-3d405921.js                                 66.36 KB   13.74 KB   11.89 KB   
    ├─ _commonjsHelpers-2c0027bd.js                             0.87 KB    0.43 KB    0.35 KB    
    ├─ index-141f1c79.js                                        28.59 KB   6.8 KB     5.78 KB    
    ├─ index-3ef843f3.js                                        378.06 KB  93.4 KB    74.89 KB   
    ├─ index-6695ea43.js                                        66.51 KB   18.32 KB   15.55 KB   
    ├─ index-e900dd09.js                                        891.16 KB  204.06 KB  159.79 KB  
    ├─ index-edc4180f.js                                        14.07 KB   3.88 KB    3.32 KB    
    ├─ react-router-e426e018.js                                 73.57 KB   17.17 KB   14.69 KB   
    ├─ times-icon-b05806d8.js                                   9.18 KB    3.11 KB    2.72 KB    
    └─ tslib.es6-2984f1e6.js                                    4.43 KB    1.77 KB    1.5 KB     


[snowpack] Proxy created: /admin -> http://localhost:8180/auth/admin/


```

**Comment by edewit** [comment]
also seems that github ran the cypress test successfully so I don't know what is going on

**Comment by mfrances17** [comment]
> also seems that github ran the cypress test successfully so I don't know what is going on

Yeah me either, I've been able to run all the other PRs without this issue. I've been running the 12.0.2 server, even just tried falling back to 11.0.2 and I get the same error. I'm not going to request changes but I won't be able to add my review to this one.

**Comment by ssilvert** [comment]
> Attempted to load the changes in your repo two days in a row, no success. Today I wiped everything clean and rebuilt from scratch, still getting the same 404 back from the server:
> `[snowpack] [404] /_dist_/clients/Advanced/index.js`

@edewit I get the same error.

**Comment by edewit** [comment]
Tried multiple things this morning and I can't reproduce this error. What do you get in the browser?

**Comment by ssilvert** [comment]
> Tried multiple things this morning and I can't reproduce this error. What do you get in the browser?

`Navigated to http://localhost:8080/'

`DevTools failed to load SourceMap: Could not parse content for http://localhost:8080/stdin.map: Unexpected token < in JSON at position 0       
`ClientDetails.js:39`

`GET http://localhost:8080/_dist_/clients/Advanced/index.js net::ERR_ABORTED 404 (Not Found)`
` hmr.js:7 `

`[ESM-HMR] listening for file changes...`

**Comment by edewit** [comment]
@ssilvert @mfrances17 have you done a `yarn install` before testing?

**Comment by ssilvert** [comment]
> @ssilvert @mfrances17 have you done a `yarn install` before testing?

Yes.

**Review by ssilvert — COMMENTED** [review]
Push gets 404 error.

If I try to push when there is no admin URL configured, I should get a warning.

Notice in old console, `Push` button has help text.  We should not have hover text like that on a button, but I think it would be appropriate to have some helper text somewhere for that.  IMO, it would be ideal to have inline help text for the whole section like we do for `Fine grain OpenID connect configuration` section.

If I click `Set to now` or `Clear`, that results in 10 (identical?) REST calls.  http://localhost:8080/admin/realms/master/clients/1aafceef-b2f8-452c-8d82-8a1f4f331e8d/installation/providers/keycloak-oidc-keycloak-json

`Register node manually` doesn't work.  Looks like path has extra slash.

Buttons and table in `Registered cluster nodes` not aligned properly.  No pagination for table?

Does `Test cluster availability` work?  I'm not sure where that came from in the old console?

`Fine grain OpenId connect configuration` should not show up for SAML clients.  It should have `Fine Grain SAML Endpoint Configuration` instead.

In old console, there is a `Valid Request URIs` field(s) in the `Fine grain OpenId connect configuration`.  We need to know where that went in the new design?

In `Open ID Connect Compatibly Modes`, need to find out what happened to `Use Refresh Tokens For Client Credentials Grant`, which appears in old console.

Also need to check on fields that appear in `Advanced Settings` in old console but are not in the new design.

`Reload` button doesn't work on `Advanced Settings`

**Comment by ssilvert** [comment]
@edewit We are at the deadline.  There is a lot of stuff to fix here and I've only done testing but I haven't looked at the code yet.  Wondering how we should move forward.

I think maybe the thing to do would be to merge this and then come back and complete each section in a separate PR along with a Cypress script for each.  Note that some sections are different for SAML vs OpeinID connect.  So each could be a PR on its own.

WDYT?

**Comment by edewit** [comment]
image

**Comment by edewit** [comment]
> Notice in old console, Push button has help text. We should not have hover text like that on a button, but I think it would be appropriate to have some helper text somewhere for that. IMO, it would be ideal to have inline help text for the whole section like we do for Fine grain OpenID connect configuration section.

@xianli123, @yih-wang what do you think about something like that?

**Comment by yih-wang** [comment]
> > Notice in old console, Push button has help text. We should not have hover text like that on a button, but I think it would be appropriate to have some helper text somewhere for that. IMO, it would be ideal to have inline help text for the whole section like we do for Fine grain OpenID connect configuration section.
> 
> @xianli123, @yih-wang what do you think about something like that? Also see the comments that Stan has about the design with regards to the saml based sections

@ssilvert @edewit The new design has already included this tooltip in the card descriptions.
image

**Comment by edewit** [comment]
ahh right updated the text and added the link to the settings tab, but it seems we don't have the admin url on the settings tab though

**Comment by edewit** [comment]
created issue #377

**Comment by edewit** [comment]
in the new PR: #328

**Comment by yih-wang** [comment]
> ahh right updated the text and added the link to the settings tab, but it seems we don't have the admin url on the settings tab though

We have it here 
image

**Comment by edewit** [comment]
yes but it's not on the new UI

**Comment by yih-wang** [comment]
Oh, I just remember we have changed some field names in the settings form. @xianli123 What is the Admin URL changed to?

**Comment by xianli123** [comment]
@yih-wang @edewit We haven't changed the terminology of Admin URL. You can see this field in this screen. https://marvelapp.com/prototype/908c3c3/screen/72040310

**Comment by edewit** [comment]
@yih-wang @xianli123 I just didn't add it for some reason issue #377 will fix that

**Pull request closed without merging**
