### PR TITLE
Make 'User Profile' tabs routable

### PR DESCRIPTION
**Pull request by jonkoops**
This will allow us to return to the correct path when navigating back from a nested form.

### CODE REVIEW

**Review by edewit — APPROVED** [review]
`defaultLocation` could also be the first tab, right?

**Comment by jonkoops** [comment]
> `defaultLocation` could also be the first tab, right?

It could be any location you'd like really.

**Review by jenny-s51 — APPROVED** [review]
Tabs are looking great @jonkoops ! The `defaultLocation` prop is an excellent addition. Just wanted to confirm since I'm seeing a blank screen on the `Attributes` tab ... is the `Attributes` tab still a WIP?

**Comment by jonkoops** [comment]
@jenny-s51 That is correct, the 'Attributes' tab still needs to be implemented.

**Comment by jonkoops** [comment]
I'm merging this PR even with some of the caveats it has, I've created a separate bug to resolve these issues (#1892).

**Pull request merged**
