### PR TITLE
KEYCLOAK-19785 Add GitHub issue forms to repositories

### PR DESCRIPTION
**Pull request by stianst**

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM, we might want to add the same kind of labels that the main Keycloak project expects.

**Review by mfrances17 — APPROVED** [review]
LGTM - this doesn't overwrite/break anything we've done in our repo, e.g. our own issue template, so merging it so we are consistent with keycloak should be fine.

**Comment by agagancarczyk** [comment]
Looks good, I have restarted the tests as ldap tests were failing.

**Review by agagancarczyk — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]
This obviously doesn't break any tests.  I'm merging it.

**Pull request merged**
