### PR TITLE
Initial version of the Service Account tab

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

Doesn't have any actions yet just the basic list with a toggle function. [marvel design](https://marvelapp.com/prototype/f058374/screen/71931942)

## Brief Description

initial version of design

## Verification Steps

Go to client details when client is of type "service account" then you'll have an extra tab also called "service account"

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Comment by srambach** [comment]
I don't know if I'm doing something wrong, but I can only get the table toolbar and a spinner, no content on the page.

**Comment by ssilvert** [comment]
> I don't know if I'm doing something wrong, but I can only get the table toolbar and a spinner, no content on the page.

@edewit  Same here.  There is an error in the console.

```
Uncaught (in promise) TypeError: adminClient.roles.getCompositeRolesForRealm is not a function
    at ServiceAccount.js:71
```

**Comment by edewit** [comment]
You need to do an `yarn install` to get the latest version of the `keycloak-admin-client` that has the `getCompositeRolesForRealm` function

**Comment by ssilvert** [comment]
> You need to do an `yarn install` to get the latest version of the `keycloak-admin-client` that has the `getCompositeRolesForRealm` function

@edewit I did that and yarn says `Already up-to-date.`  Looks like you need to update package.json.

**Comment by edewit** [comment]
The package.json was updated in a separate PR #234, but I found the problem. You need to save the client before you go to the service account tab. Added a commit that makes the service account tab only show after save.

**Review by srambach — COMMENTED** [review]
I still can't get the page to load even with your update, an install, and making sure the client is saved.

**Comment by ssilvert** [comment]
Tab name should be called "Service account roles"

**Comment by ssilvert** [comment]
@edewit  I'm going to break our rules and leave this open until Monday.  Normally, I would merge this PR and we can address the relatively minor issues raised by @srambach and myself separately.

However, we now have another option.  The latest PatternFly has a new Dual list selector:  https://www.patternfly.org/v4/components/dual-list-selector

It's possible that if this selector had been available then the design for this page would have ended up similar to what we have in the old console.  The nice thing is that this selector has searching, which I believe was one of the major reasons for the design change.

Regardless, we have a mandate to get this React version of admin to code complete as soon as possible.  So, if it's easier to implement like it's done in the old console then that's what we should do.  I suspect that it probably is because the REST API was designed with the old UI in mind.  Just judging by the number of REST calls required to render the old page versus the new page this looks like it's the case.

The new dual list selector is pretty nice and it does all the right things when it comes to keyboard navigation and such.  It seems to me that we could spend a lot of time perfecting the new style screens.  So if it's going to be easier to implement dual list screens like in the old console then we need to do that.

**Comment by edewit** [comment]
@srambach you'll see the page when you create a new client and check the "Service Account" checkbox:
image

**Comment by edewit** [comment]
As I see it the amount of requests needed to build this table is due to the fact that the old console doesn't display the client roles. Only when you select a client with the dropdown under the Dual list selector you can see the roles of one client.

If speed of development is a deciding factor, this page is working atm, if you want to use this Dual list selector we have to start over again.

**Comment by edewit** [comment]
Just talked with the designers and this table layout was chosen because of better UXD not because the component wasn't available.

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
Looks like cosmetic things from me and @srambach have been fixed.  Merging.

**Pull request merged**
