### PR TITLE
Added role mapping tab to group detail page

### PR DESCRIPTION
**Pull request by alevid99**
## Motivation

In the current admin console is possible to assign roles to groups and we need this functionality to adopt the new admin console in our keycloak installation

## Brief Description

Added role mapping tab to the group detail page with the same UI/UX of the role mapping tab present in the user detail page

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

**Comment by yih-wang** [comment]
* Tab name changes to "Role mapping"
* The table is supposed to be empty by default when there's no role assigned to this group. Now all the roles show up by default. The "Select all" checkbox is selected and cannot be unselected, and all the roles in the table cannot be selected.
image

Edit: when I search for something and then remove it, the table shows the empty state as intended

**Comment by jonkoops** [comment]
@alevid99 could you rebase your branch on `main` and include the review comments from @yih-wang?

**Comment by squaremarco** [comment]
I'll come back to you as soon as this commit gets merged https://github.com/keycloak/keycloak-nodejs-admin-client/pull/322 and it goes live on npm.

**Comment by squaremarco** [comment]
Alright, I've rebased the branch as you asked and integrated the changes of `keycloak-nodejs-admin-client` https://github.com/keycloak/keycloak-nodejs-admin-client/pull/322
Let me know if there's something else to do.

**Comment by jonkoops** [comment]
@yih-wang could you take another look to see if this matches the UDX expectations?

**Review by jonkoops — APPROVED** [review]
Code-wise this PR is looking good to me

**Review by edewit — APPROVED** [review]
:+1:

**Comment by jonkoops** [comment]
Thanks again @squaremarco!

**Pull request merged**
