### PR TITLE
removed useEffect data load instead uses fetch

### PR DESCRIPTION
**Pull request by edewit**
fixes: #1025

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Review by mfrances17 — CHANGES_REQUESTED** [review]
i'm no longer able to create a new kerberos user fed provider with these changes..

kerberos

the routing will probably need to change if you want to implement changes like this, i assume. it's looking for the 'new' resource instead of doing the proper routing to add if it's 'new'.

**Comment by edewit** [comment]
@mfrances17 don't know what your issue is, but as you can see I didn't update the routing

**Review by mfrances17 — APPROVED** [review]
I'll run a clean and retest, it could be an issue on my end.

**Comment by mfrances17** [comment]
@edewit actually, the kerberos user fed test is failing with these changes, that test has been rock solid to this point. i would verify that you did not break the test.

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Changing from approved to request changes just until i retest

**Comment by mfrances17** [comment]
@edewit yes, this is still failing after a clean build. did you test creating a new Kerberos user fed provider? these changes break it, which is why i assume the test is failing as well. you did not change the route, but the existing route depends on 'new'.

**Review by mfrances17 — APPROVED** [review]
LGTM, issue with creating a new kerberos provider is fixed, works great now

**Pull request merged**
