### PR TITLE
initial version realm settings section

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

First tab of the realm section

## Brief Description

Give all sections something to do, also makes the console more useable ;)

## Verification Steps

Go to there realm section, enable / disable / delete and save work. Partial export / imports don't

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
Tested it out and it looks really good.  Only problem I found was that "Reload" doesn't work.

I'll review the code later.

**Comment by edewit** [comment]
what should reload do?

**Comment by ssilvert** [comment]
> what should reload do?

That's a very good question because I don't think we have properly defined this application-wide.  It probably means the same as the HTML input type "reset".  But we need some more clarification on refresh/reload/reset/cancel.  I'll start a discussion on it.

**Comment by edewit** [comment]
right because on the realm role pages it navigates to the list again.... I could do a reset of the form back to the original state

**Comment by edewit** [comment]
maybe we merge this as is and clarify the reload later?

**Comment by ssilvert** [comment]
> maybe we merge this as is and clarify the reload later?

It's clarified now.  `Reload` is the word we use for the action that means, "Don't save. Reload my form data and start over."

**Comment by ssilvert** [comment]
@edewit Please fix conflict.

**Review by mfrances17 — APPROVED** [review]
LGTM... reviewed the code and it looks good. Also tested the functionality by creating a new realm and running all the enabled commands.

One caveat, when deleting a realm it works great on the backend but the existing realm is still selectable in the realm drop-down in the new UI. This can lead to some funky behavior/invalid URLs. Worked fine after a refresh. Not sure if we may want to do an automatic reload and default back to another realm in this scenario... not sure the best solution. But i think this can be merged and maybe we file that as a separate potential issue.

**Comment by edewit** [comment]
@mfrances17 this refresh was handled in another PR, I've rebased this one so that you can see that the realm list is now updated after you delete a realm

**Comment by mfrances17** [comment]
@edewit yep, i just tested the rebased version and the realm list is handled nicely. great work. i already approved but am approving again. :)

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
