### PR TITLE
always show realm add button and filter on keystroke

### PR DESCRIPTION
**Pull request by edewit**
fixes: #101

### CODE REVIEW

**Review by ssilvert — COMMENTED** [review]
I like the new "search on keystroke" functionality.  Seems perfect for this kind of search.

@srambach Please review the css.

There are still issues with this component but I'd like to move on.  So it's ok if we address them later as long as the css meets our coding standards:

- Add Realm button needs gutters.
- Check mark for current realm should be right justified.

https://marvelapp.com/prototype/ei9eebh/screen/71477803

**Comment by edewit** [comment]
issues logged in #97

**Comment by edewit** [comment]
@srambach thanks, looks great now!

fixes: #97

**Comment by ssilvert** [comment]
@edewit Please fix the build on this one.

**Review by jenny-s51 — APPROVED** [review]
Looks great!

**Pull request merged**
