### PR TITLE
Create custom user federation providers page

### PR DESCRIPTION
**Pull request by edewit**
fixes: #1722

### CODE REVIEW

**Comment by edewit** [comment]
To test this download this jar:
[custom-user-provider-1.0-SNAPSHOT.zip](https://github.com/keycloak/keycloak-admin-ui/files/7746294/custom-user-provider-1.0-SNAPSHOT.zip)
rename it to `custom-user-provider-1.0-SNAPSHOT.jar`

run the jboss cli:
```
./bin/jboss-cli.sh --controller=127.0.0.1:10090 --command="module add --name=ch.nerdin.keycloak.users --resources=./custom-user-provider-1.0-SNAPSHOT.jar --dependencies=org.keycloak.keycloak-core,org.keycloak.keycloak-server-spi"
```
Then open `standalone.xml` and find the section `<web-context>auth</web-context>`
There add an provider:
```xml
        <subsystem xmlns="urn:jboss:domain:keycloak-server:1.1">
            <web-context>auth</web-context>
            <providers>
                <provider>
                    classpath:${jboss.home.dir}/providers/*
                </provider>
                <provider>module:ch.nerdin.keycloak.users</provider>
            </providers>
<!-- .... -->
```
Then when you restart you should have a custom user federation provider:

image

**Comment by yih-wang** [comment]
The breadcrumb is missing on the creation/detail page.
image

Should be 

_User federation > Add custom provider_ on Creation page

_User federation > Provider details_ on details page

**Comment by edewit** [comment]
@yih-wang done

**Review by mfrances17 — APPROVED** [review]
LGTM, was able to get the Add Custom-user-provider card to the User Fed landing page by modifying the keycloak server as described, and then add/delete a custom user fed provider using the new admin console UI.

**Pull request merged**
