### PR TITLE
fixing issue 629

### PR DESCRIPTION
**Pull request by edewit**
fixing: #629

### CODE REVIEW

**Comment by ssilvert** [comment]
@yih-wang Please review.

**Review by yih-wang — CHANGES_REQUESTED** [review]
Here are the issues that haven't been addressed 

[Issue 1 - Groups list]
> When I search in the list and there is no matched result. The default empty state displays and ask the user to create a group, which doesn't make sense here. We can show a simple no result screen to users. Reference the Roles list screen I paste below.
image

[Issue 2 - Global search]
> A breadcrumb is missing so I can't find a way to return to the group list.
image

The design has been updated in the original link, you can reference [this screen](https://marvelapp.com/prototype/228971ig/screen/79872064)

[Issue 3 - Global search]
> This page hasn't been updated so its style is obviously not aligned with all other pages (it's in the old style we used to apply). Can we adjust the background and table to the same as other pages?
image

The design has been updated in the original link, you can reference [this screen](https://marvelapp.com/prototype/228971ig/screen/79872065)

**Comment by yih-wang** [comment]
I'll open a separate issue for the "Move to" function so don't cover the issues of it in this thread.

**Comment by edewit** [comment]
@yih-wang so this one is good?

**Comment by ssilvert** [comment]
@yih-wang I'm going to go ahead and merge this.  Please create issues for any remaining work.

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
