### PR TITLE
Use realm name in urls

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

In order to create links that are "bookmarkable" we should add the realm name in the url

## Brief Description

Update the code to create urls like: `/realm/section/` so that you could share links

## Verification Steps

Navigate to any page to see the realm name in the url

## Checklist:

- [x] Code has been tested locally by PR requester
- [N] User-visible strings are using the react-i18next framework (useTranslation)
- [N] Help has been implemented
- [N] axe report has been run and resulting a11y issues have been resolved
- [N] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Review by mfrances17 — CHANGES_REQUESTED** [review]
One small unneeded import... also, testing went great but noticed that just going to "localhost:8080" will go to page not found, it is now expecting "localhost:8080/master" which goes to the default client view. is that intended behavior for users if they just put in the hostname with no realm?

**Comment by edewit** [comment]
@mfrances17 ahh no, your right lets make localhost:8080 got to the client list as well for now.

**Review by jenny-s51 — APPROVED** [review]
LGTM @edewit ! Your PR is a great lesson on how to use the `useRouteMatch` hook from react-router! Working as expected. 👍

**Comment by ssilvert** [comment]
@edewit This is definitely needed, but I couldn't get it to work.  Looks like it is working for others so I must be doing something wrong?

I go to http://localhost:8080/master/users.  Then when I try to switch realms it just goes back to http://localhost:8080/master/users.

**Comment by edewit** [comment]
https://user-images.githubusercontent.com/51133/103618180-c5788800-4f2f-11eb-8f86-c54ffc0fdbfe.mov

It works for me, don't know why it doesn't for you.

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
> It works for me, don't know why it doesn't for you.

I think my database was corrupted.  Rebuilt the DB and it worked.

**Pull request merged**
