### PR TITLE
Sub group navigation in groups section

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

This adds the ability to click on group names to navigate the sub groups

## Brief Description

Introduces specialized breadcrumb, because it's basiclly the same page

## Verification Steps

Go to old admin console and create a group with subgroups then on the groups section click that groups link

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
Found a bug:
1. Create subgroups A -> B -> C
2. In another tab, go to groups and delete B
3. Go back to the original tab and click on B in the breadcrumb.

`GroupBreadCrumbs.js:59 Uncaught (in promise) TypeError: Cannot read property 'name' of null
    at GroupBreadCrumbs.js:59`

**Review by jenny-s51 — CHANGES_REQUESTED** [review]
getting the same error as @ssilvert when testing! also can we change the `ariaLabel` and `searchPlaceholderKey` on lines 189 and 190 of `GroupsSection.tsx` to refer to groups rather than client scopes? Otherwise looking good 👍

**Comment by ssilvert** [comment]
> Found a bug:
> 
> 1. Create subgroups A -> B -> C
> 2. In another tab, go to groups and delete B
> 3. Go back to the original tab and click on B in the breadcrumb.
> 
> `GroupBreadCrumbs.js:59 Uncaught (in promise) TypeError: Cannot read property 'name' of null at GroupBreadCrumbs.js:59`

@edewit If I delete group `A` in this scenario there is still a problem.  If a first-level group got deleted in another tab it should go back to the group list when you click on the `A` breadcrumb link.

**Comment by edewit** [comment]
@ssilvert added redirect

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
