### PR TITLE
merged "new role form" and "role details" into one

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

The create new role and role detail form are almost identical, so I thought it would be nice to merge them

## Verification Steps

Creating and editing roles, should still work

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Comment by ssilvert** [comment]
@edewit There is a warning in the console when you create a new role for the first time.  But it looks like it was there in the old code as well.  I think I saw where you fixed this problem on another page?
```
Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in textarea (created by TextArea)
```

**Comment by ssilvert** [comment]
@jenny-s51 Can you review this?

**Comment by edewit** [comment]
> @edewit There is a warning in the console when you create a new role for the first time. But it looks like it was there in the old code as well. I think I saw where you fixed this problem on another page?
> 
> ```
> Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     in textarea (created by TextArea)
> ```

This is a know issue, I'll fix it soon #230

**Review by jenny-s51 — APPROVED** [review]
Great updates @edewit , thank you for making these changes

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
