### PR TITLE
update the admin client to the latest version

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Was the removal of the additions to the RolesRepresentation type intentional? Seems unrelated to updating the admin client to the latest version - but regardless, 'name' doesn't exist without adding to the type but is referenced in a couple of places in the component.

**Comment by edewit** [comment]
@mfrances17 the defined types where a workaround because they where not right in the admin client. Now that they are right in the admin client we can / must remove them here

**Comment by mfrances17** [comment]
ah, ok thanks @edewit... maybe i didn't pull in the latest admin client successfully when i tested? i'll retest.

**Review by mfrances17 — APPROVED** [review]
LGTM, not getting any errors - suspect i did not have had the latest admin client when originally tested.

**Pull request merged**
