### PR TITLE
Initial version of the identity providers section

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

Adds the ability to create list and delete identity providers + the ability to change the display order.

## Brief Description

see [marvel](https://marvelapp.com/prototype/55c2d8f/screen/75697040)

## Verification Steps

Go to the identity provider section click on one of the providers then save to see the list create another to verify the order change dialog.

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Comment by edewit** [comment]
image

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Initial functionality worked well - i was able to successfully create three identify providers, change the display order, log out, and verify that the providers were listed in the desired order in the login screen. Two minor suggestions:

- When you add a provider successfully, you remain on the same Add provider screen. You should be navigated back to the provider list.
- When you delete a provider, the provider is successfully deleted but the list is not refreshed so you won't see it removed from the list unless you navigate away and back again (this may sound familiar) :)

**Comment by edewit** [comment]
fixed those two points... though the navigation back to the list is wrong, it should go to a more detailed edit page, but that is not there yet so guess going back to the list is fine for now.

**Review by mfrances17 — APPROVED** [review]

**Review by mfrances17 — APPROVED** [review]
LGTM - latest changes work great

**Pull request merged**
