### PR TITLE
Fixing UXD review for user

### PR DESCRIPTION
**Pull request by edewit**
fixing: #640

### CODE REVIEW

**Comment by ssilvert** [comment]
@yih-wang Please review.

**Review by yih-wang — CHANGES_REQUESTED** [review]
The issue of Required actions is still there - each time I click "Show more"/"Show less"/the close icon in the chip, the dropdown will be opened/closed - it shouldn't be influenced. Reference the [PF component](https://www.patternfly.org/v4/components/select#multiple). 

Also, a new option "Update User locale" is added to the menu in the latest Keycloak version. Do I need to raise this request in a separate issue?
 image

For the "Join groups" modal, I think there's still something that needs to be discussed. And I'm wondering if it is reusing the component of the "Move to" group modal. It may make more sense to open a new issue tracking this so that it won't block this pr.

**Comment by edewit** [comment]
@yih-wang This is what the patternfly component does has the same behavior as the reference page that you link

**Comment by ssilvert** [comment]
I'm merging this now.

@yih-wang Please open issues for anything remaining that needs attention.

**Pull request merged**
