### PR TITLE
Use number input for max lifespan

### PR DESCRIPTION
**Pull request by mfrances17**
## Motivation
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1810.

## Brief Description
Changed Max Lifespan from text field to number input.

## Verification Steps
Verify that implementation matches design outlined in https://github.com/keycloak/keycloak-admin-ui/issues/1810 and that you can still save/retrieve values correctly.

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] Unit tests have been created/updated

## Additional Notes
None

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Review by jenny-s51 — APPROVED** [review]
LGTM! Saving/setting max lifespan works as expected and the value is written successfully

**Review by jonkoops — APPROVED** [review]

**Comment by agagancarczyk** [comment]
@mfrances17 I have run the tests locally twice and the result was the same. The same two tests were failing. Could you please take a look at this? Thanks

Screenshot 2022-04-01 at 17 39 45

**Comment by mfrances17** [comment]
@agagancarczyk thanks - the clients test issue is unrelated, there's nothing in this code change that is invoked by clients. but i did run it locally and it passed for me. you should clean your server db and re-run the tests. the kerberos test fail is legit though, i will put up a fix.

**Comment by mfrances17** [comment]
@agagancarczyk added fix for the kerberos test, it's passing locally now

**Pull request merged**
