### PR TITLE
Support for post_logout_redirect_uris in OIDC client registration

### LINKED ISSUE #2984: Support for post_logout_redirect_uris in OIDC client registration
We need to be able to handle the post logout redirect Uris for a client in the same way we handle redirect Uris. This links directly with https://github.com/keycloak/keycloak/issues/10135 and https://github.com/keycloak/keycloak/pull/12282.

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #2984

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM. @xianli123 could you confirm this is something we want UX-wise?

**Comment by xianli123** [comment]
Hi @jonkoops , @douglaspalmer Sorry for the late reply. I tried to switch the branch to this one and view the UI. But I failed. Could you please help me run this branch? Or share some UI screenshots that you implemented with me? Thanks!

**Comment by mposolda** [comment]
@jonkoops It will be great to have this PR included in Keycloak 19, which has deadline quite soon. Is it possible to merge this PR based on your approval and eventually polish the UI later (if @xianli123 has any feedback for improving the UI part?)

**Comment by xianli123** [comment]
> you may also need the build of keycloak with changes from this PR included https://github.com/keycloak/keycloak/pull/12282 .

Hi @mposolda , thanks for your reminder. But I don't know how to run it. What should I do? Are there any toturials help me to run it? Thanks!

**Comment by xianli123** [comment]
> Is it possible to merge this PR based on your approval and eventually polish the UI later (if @xianli123 has any feedback for improving the UI part?)

I agree.

**Comment by douglaspalmer** [comment]
Screenshots of the changes:

Empty post logout redirect uri field.
Screen Shot 2022-07-22 at 9 05 26 PM

One valid post logout redirect uri.
Screen Shot 2022-07-22 at 9 04 29 PM

Two valid post logout redirect uris.
Screen Shot 2022-07-22 at 9 05 02 PM

Use valid redirect uris for valid post logout redirect uris.
Screen Shot 2022-07-22 at 9 04 00 PM

**Comment by jonkoops** [comment]
Yeah, I have no issue merging this in now. Perhaps Kun can judge the screenshots as a means of approval?

**Comment by xianli123** [comment]
Hi @douglaspalmer @jonkoops @mposolda Thanks!  Most of them look good to me. But one detail about  the "Two valid post logout redirect uris" as quoted below should be optimized.
Both uris should be able to be deleted. So all remove icons after this line should be clickable. The same thing happens to the "Valid redirect URIs". What do you think?

> Two valid post logout redirect uris. 
image

**Comment by mposolda** [comment]
@xianli123 As you pointed, this issue is not specific to the new switch added in this PR. The @douglaspalmer followed the same pattern, which was already used by existing switches like "Valid Redirect URIs". In other words, this issue is not specific to the new switch "Post Logout Redirect URIs".

So I suggest to merge this PR and then make sure that there is follow-up PR for the UXD issue and make sure that it is fixed altogether for all the switches with multiple values. Besides "Valid Redirect URIs" and "Post Logout Redirect URIs", there are few more such switches on the client (EG. Request URIs). WDYT?

**Comment by xianli123** [comment]
Hi @mposolda Yes, that makes more sense. I can create a separate issue for multiple values. Let's merge it for now. Thanks!

**Comment by mposolda** [comment]
@xianli123 @jonkoops Thanks!

**Pull request merged**
