### PR TITLE
Fix misformed Cypress config for GitHub Action

### PR DESCRIPTION
**Pull request by jonkoops**

### CODE REVIEW

**Comment by jonkoops** [comment]
Looks like some of the Cypress tests are failing, I don't think this is due to my change but I have not verified this.

**Comment by edewit** [comment]
re-running the jobs to be sure

**Comment by jonkoops** [comment]
Running the tests locally, I am seeing similar test failures. My guess is some code changes broke the tests or they are just a bit flaky for some reason.

**Comment by edewit** [comment]
@jonkoops you just discovered that our tests haven't run quite a while and have given a false positive. Working on fixing them now in [this branch](https://github.com/keycloak/keycloak-admin-ui/tree/fixing-cypress-tests)

**Comment by jonkoops** [comment]
Awesome, thanks for looking into it! Once those are fixed I can give this PR a rebase so we can see if the CI also picks things up nicely.

**Comment by edewit** [comment]
@jonkoops no need already put your commit into that branch and create a PR (#586) so I'll close this one. It still needs some work to make all of them pass though

**Pull request closed without merging**
