### PR TITLE
added user role mapping tab to user details

### PR DESCRIPTION
**Pull request by edewit**
## Motivation
Part of the user details

## Verification Steps

Go to user details and see the new role mapping tab

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]

**Comment by ssilvert** [comment]
@edewit I'd like to review this one today.  Can you fix the conflict?

**Comment by edewit** [comment]
@ssilvert rebased again

**Comment by edewit** [comment]
rebased again...

**Review by mfrances17 — APPROVED** [review]
LGTM... code looks good and functionality worked as expected.

**Comment by edewit** [comment]
@ssilvert rebased again...

**Pull request merged**
