### PR TITLE
created a MockAdminClient for the storybook

### PR DESCRIPTION
**Pull request by edewit**
## Motivation

To be able to have stories that use the `<FormAccess` and backend data, I introduced a mock that helps with that

## Brief Description

fixed all broken stories and updated storybook to version 6.1.7

## Checklist:

- [x] Code has been tested locally by PR requester
- [NA] User-visible strings are using the react-i18next framework (useTranslation)
- [NA] Help has been implemented
- [NA] axe report has been run and resulting a11y issues have been resolved
- [NA] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Comment by srambach** [comment]
This is great, much needed. Can you give more information about how to use it?

**Comment by ssilvert** [comment]
> This is great, much needed. Can you give more information about how to use it?

Good question.

@edewit What is the most appropriate way to document this?

**Comment by edewit** [comment]
It's quite simple really most components need to fetch data and use the context to get an `adminClient` instance. Now I introduced a `<MockAdminClient>` that you can wrap around the component you want to create a storybook for. If you want your component to fetch some mock data then you can add it in the `mock` attribute like this:

```jsx
<MockAdminClient mock={{ roles: { findOneById: () => mockJson } }}>
   <RoleComponent />
</MockAdminClient>
```
This will mock the `roles` endpoint `findOneById` and return your `mockJson`.

**Comment by edewit** [comment]
@ssilvert I can add some documentation on the `MockAdminClient`?

**Comment by ssilvert** [comment]
> @ssilvert I can add some documentation on the `MockAdminClient`?

@edewit Sounds good.  Maybe use TSDoc?

**Comment by edewit** [comment]
right, added

**Review by ssilvert — APPROVED** [review]
@edewit LGTM.  Just need to fix conflict.

**Comment by srambach** [comment]
Trying to follow this :) Will it be able to make a Storybook control that switches the whoAmI so that you can check the component's (form's) appearance as different roles?

**Comment by ssilvert** [comment]
> Trying to follow this :) Will it be able to make a Storybook control that switches the whoAmI so that you can check the component's (form's) appearance as different roles?

@srambach I'm pretty sure the answer is "yes".  I'm going to go ahead and merge.  @edewit can answer your question on Monday.

**Pull request merged**
