### PR TITLE
Remove arbitrary margin from bottom of forms

### LINKED ISSUE #2688: [UX Review] Fine-tune the layout of SAML Keys tab
### Describe the bug

In the Keys tab of the SAML client, the distance between the 2 parts should be 24px, as shown in the screenshot below. The same thing happens to the **Encryption keys config** below.

Screen Shot 2022-05-23 at 15 05 43

### Version

Admin new UI

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #2688.

### CODE REVIEW

**Comment by edewit** [comment]
@jonkoops this is used everywhere are you sure we can remove it?

**Comment by jonkoops** [comment]
@edewit Yeah, I checked a lot of the places this was used and it seemed to not impact the layout negatively (actually improved some). I have however not checked every screen so there could be some regressions.

**Review by edewit — APPROVED** [review]

**Review by agagancarczyk — APPROVED** [review]

**Comment by xianli123** [comment]
Hi @jonkoops , I've seen the new UI, but I found the distance is also a bit larger than the design. The distance between the 2 parts should be 24 px. Could you please check it again. Thanks!

**Comment by jonkoops** [comment]
@xianli123 I've removed the additional padding from the cards, could you take another look?

**Comment by xianli123** [comment]
@jonkoops It looks good to me. Thanks.

**Review by xianli123 — APPROVED** [review]

**Pull request merged**
