### PR TITLE
fixing issues described in 595

### PR DESCRIPTION
**Pull request by edewit**
fixing: #595

### CODE REVIEW

**Review by mfrances17 — CHANGES_REQUESTED** [review]
could be user error, but i don't see a visible option to show/hide metadata option when creating an openID Connect provider:
no-metadata

also, when viewing settings of an existing openid connect provider, looks like an extra divider is being shown:
extra-divider

**Comment by edewit** [comment]
@mfrances17 this option is available after you have used an url to load this information put in `http://localhost:8180/auth/realms/master/.well-known/openid-configuration` as a discovery endpoint to see that

**Comment by mfrances17** [comment]
> @mfrances17 this option is available after you have used an url to load this information put in `http://localhost:8180/auth/realms/master/.well-known/openid-configuration` as a discovery endpoint to see that

Ah, ok... yes that worked great. Thanks for the info.

**Review by mfrances17 — APPROVED** [review]
LGTM, code is good and it looks like all of the issues were addressed in my testing.

**Pull request merged**
