### PR TITLE
Upgrade PatternFly to a prerelease version

### PR DESCRIPTION
**Pull request by jonkoops**
## Motivation
There are some fixes in PatternFly that are needed for the the Snowpack 3 (https://github.com/keycloak/keycloak-admin-ui/pull/839) upgrade that are only available in a prerelease version.

### CODE REVIEW

**Comment by jonkoops** [comment]
There is a styling issue after this upgrade which breaks the toolbars.
image

**Review by agagancarczyk — APPROVED** [review]
The proposed version of patternfly/patternfly is correct.

**Review by edewit — CHANGES_REQUESTED** [review]
Could you have a look and fix this css in this PR as well?

**Review by jenny-s51 — APPROVED** [review]
LGTM! 👍 Fixed toolbar CSS @jonkoops @edewit

**Comment by jonkoops** [comment]
Thanks @jenny-s51, it's much appreciated!

**Review by edewit — APPROVED** [review]

**Pull request merged**
