### PR TITLE
Fixed issue using import

### PR DESCRIPTION
**Pull request by edewit**
fixes: #355

### CODE REVIEW

**Review by jenny-s51 — COMMENTED** [review]
The client id and description text fields are populating correctly based on the imported data. what is the best way to test the import itself @edewit ? 

I created a sample JSON file to resemble some of the attributes in the mock: 

```
{
    "clientId": "test",
    "description": "test description",
    "adminUrl": "",
    "baseUrl": "asjdlajsd.com",
    "surrogateAuthRequired": false
    
}
```

But when I click "save" I get a 500 error.

**Comment by edewit** [comment]
you can create an export of an existing client, by clicking on the action menu - export:

image

And then delete that client and use the downloaded json to recreate it.

**Review by ssilvert — CHANGES_REQUESTED** [review]
- When I try to drag a file to import, I get "Are you sure you want to clear this file?" dialog.
- I don't think you should be able to edit the json after importing, but I'm open to opposing views.  Just seems error-prone.
- Client authorization can only be set to true if accessType=confidential.  So if you set it and try to save a public client you will get an error.  Look at accessType in the old console.  There are other things that only apply to certain access types.  This is also a problem in the wizard.
- BTW, if you are wondering how you know what the accessType is from the json, it appears to be determined with a combination of the bearerOnly and publicClient flags.
- If I go to the details screen and save something, the settings for Capability config disappear.

**Comment by edewit** [comment]
@ssilvert so this is an error in the design as currently there is no accessType

**Comment by edewit** [comment]
@ssilvert so this is a error in the UI design we need this accessType dropdown on the pages? @yih-wang?

**Comment by edewit** [comment]
can we merge this @ssilvert there is an issue with regards to the Client authorization #392

**Review by ssilvert — APPROVED** [review]
We can merge this and handle the rest of the feedback as issue.

**Pull request merged**
